### ISSUE TITLE
Error upon importing google.storage due to six location issues

### ISSUE THREAD

**Issue by tomthebuzz** [robinvanschaik/flair-on-gcp#1]
Thx for your excellent explanation and approach. Eager to try out.

Error upon import says:
cannot import name 'collections_abc' from 'six.moves' (unknown location)

Have updated to latest SIX version (1.15) but still get the error.
Any hints?

**Comment by robinvanschaik** [comment]
Hi @tomthebuzz, 

The unknown location import happens with Google Cloud packages, such as Google BigQuery and Google Cloud Storage, from time to time.

For instance see googleapis/google-cloud-python#2464 And  googleapis/google-cloud-python#9965

I should have pinned the versions of all the required packages in the Docker images, rather than installing the most up-to-date versions. 

I can probably take care of this on Tuesday.
